/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;
import java.util.Random;

public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAkinator = new javax.swing.JPanel();
        lblfaladoGenio = new javax.swing.JLabel();
        lblGenio = new javax.swing.JLabel();
        lblbalaodeFala = new javax.swing.JLabel();
        btnPalpite = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlAkinator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblfaladoGenio.setText("Penso em um número inteiro de 1 a 5. Advinhe!");
        pnlAkinator.add(lblfaladoGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 300, 50));

        lblGenio.setIcon(new javax.swing.ImageIcon("C:\\Users\\Casa\\Desktop\\Projetos ajva\\POO\\br.com.ifba.atividade04\\src\\br\\com\\ifba\\atividade04\\image\\akinator-removebg-preview.png")); // NOI18N
        pnlAkinator.add(lblGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 355, 308));

        lblbalaodeFala.setIcon(new javax.swing.ImageIcon("C:\\Users\\Casa\\Desktop\\Projetos ajva\\POO\\br.com.ifba.atividade04\\src\\br\\com\\ifba\\atividade04\\image\\balãop_de_fala-removebg-preview.png")); // NOI18N
        pnlAkinator.add(lblbalaodeFala, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 410, -1));

        btnPalpite.setText("Palpitar");
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpiteActionPerformed(evt);
            }
        });
        pnlAkinator.add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));
        pnlAkinator.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlAkinator, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlAkinator, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        Random random = new Random();// criando a nova instancia random
        
        int numdoGenio = random.nextInt(5) + 1;// vai setar na variavel um numero int entre 1 e 5
        
        int palpitedoUser = (int) jSpinner1.getValue();
        
        if(palpitedoUser <1 || palpitedoUser >5){//verificar se esta dentro do que o genio determinou
            
            lblfaladoGenio.setText("Este valor não está entre 1 e 5");
            
        } else if(palpitedoUser == numdoGenio) {
            
        lblfaladoGenio.setText("Acertou!");
        
        } else{
            
        lblfaladoGenio.setText("Errado! Pensei no: "+numdoGenio);
  
        }
        
    }//GEN-LAST:event_btnPalpiteActionPerformed

    /** 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblGenio;
    private javax.swing.JLabel lblbalaodeFala;
    private javax.swing.JLabel lblfaladoGenio;
    private javax.swing.JPanel pnlAkinator;
    // End of variables declaration//GEN-END:variables
}
