/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade03.view;

/**
 *
 * @author Casa
 */

import java.time.Year;

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncalcularIdade = new javax.swing.JButton();
        spnanoNascimento = new javax.swing.JSpinner();
        lblPergunta = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblimageIdade = new javax.swing.JLabel();
        lblidadeResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btncalcularIdade.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btncalcularIdade.setIcon(new javax.swing.ImageIcon("C:\\Users\\Casa\\Downloads\\calculadora.icon-removebg-preview.png")); // NOI18N
        btncalcularIdade.setText("Calcular");
        btncalcularIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularIdadeActionPerformed(evt);
            }
        });

        lblPergunta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPergunta.setText("Digite o seu ano de nascimento para determinarmos sua idade");

        lblIdade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIdade.setText("Idade:");

        lblimageIdade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication4/idade.icon-removebg-preview.png"))); // NOI18N
        lblimageIdade.setText("jLabel1");

        lblidadeResultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPergunta)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btncalcularIdade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblimageIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIdade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblidadeResultado))
                    .addComponent(spnanoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPergunta)
                    .addComponent(spnanoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIdade)
                        .addComponent(lblidadeResultado))
                    .addComponent(btncalcularIdade)
                    .addComponent(lblimageIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncalcularIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularIdadeActionPerformed
      
        int anoAtual = Year.now().getValue();//receber o ano que esta na  maquina
        int anoNascimento = (int) spnanoNascimento.getValue();
        int idade = anoAtual - anoNascimento;
            
        String idadeString = Integer.toString(idade);
        
        if(anoNascimento > anoAtual ){
            
            lblidadeResultado.setText("ANO INVÁLIDO!");
            //apos 2 seg depois da  mensagem aparecer  no label ele será limpo | para interface usar essa sintaxe em específico
            new javax.swing.Timer(2000, e -> {//definie  açao em miliseg
                lblidadeResultado.setText("");//reseta o campo de texto
            ((javax.swing.Timer)e.getSource()).stop();//chama o timer e  encerra-o
        }).start();//iniciar o timer
            
        } 
        else if(anoNascimento < anoAtual - 122){//baseado em Jeanne Calmet, a pessoa que comprovadamente mais viveu na história
            
        lblidadeResultado.setText("ANO INVÁLIDO!(MUITO ANTIGO!!)");
            
            new javax.swing.Timer(2000, e -> {//apos 2 seg depois da  mensagem aparecer  no label ele será limpo
            lblidadeResultado.setText("");
            ((javax.swing.Timer)e.getSource()).stop();
        }).start();
        
        }else{
            
        lblidadeResultado.setText(idadeString);
        
        }
    }//GEN-LAST:event_btncalcularIdadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcularIdade;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblPergunta;
    private javax.swing.JLabel lblidadeResultado;
    private javax.swing.JLabel lblimageIdade;
    private javax.swing.JSpinner spnanoNascimento;
    // End of variables declaration//GEN-END:variables
}
